---
name: Release

on:
  push:
    branches:
      - master
    # tags:
    #   - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: "true"

jobs:
  release-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: macos-15
          #   target: aarch64-apple-darwin
          #   binary: neocmakelsp
          # - os: macos-15-intel
          #   target: x86_64-apple-darwin
          #   binary: neocmakelsp
          # - os: ubuntu-24.04
          #   target: x86_64-unknown-linux-gnu
          #   binary: neocmakelsp
          # - os: ubuntu-24.04
          #   target: x86_64-unknown-linux-musl
          #   binary: neocmakelsp
          # - os: ubuntu-24.04-arm
          #   target: aarch64-unknown-linux-gnu
          #   binary: neocmakelsp
          # - os: ubuntu-24.04-arm
          #   target: aarch64-unknown-linux-musl
          #   binary: neocmakelsp
          - os: windows-2025
            target: x86_64-pc-windows-msvc
            binary: neocmakelsp.exe
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            binary: neocmakelsp.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.target }}
      - uses: mlugg/setup-zig@v2
        if: ${{ ! startsWith(matrix.os, 'windows') }}
      - uses: taiki-e/install-action@v2
        if: ${{ ! startsWith(matrix.os, 'windows') }}
        with:
          tool: cargo-zigbuild
      - name: cargo zigbuild
        if: ${{ ! startsWith(matrix.os, 'windows') }}
        run: cargo zigbuild --release --target ${{ matrix.target }}${{ endsWith(matrix.target, 'gnu') && '.2.17' || '' }}
      - name: cargo build
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: cargo build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.binary }}

      # - name: Publish to crates.io
      #   if: github.event_name != 'workflow_dispatch'
      #   run: cargo publish --token ${{ secrets.CRATE_TOKEN }}

  release:
    needs: release-build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v6
      - uses: taiki-e/install-action@v2
        with:
          tool: fd-find
      - run: fd -I -t f neocmakelsp
